### ISSUE TITLE
Getting an unorderable types: F() < int() in the query

### ISSUE THREAD

**Issue by zedan185** [andilabs/django-tinder#1]
The following query
```
candidates_inside_finder_radius_and_vice_versa = candidates.filter(
        last_location__distance_lte=(
            finder_location,
            D(km=min(finder.prefered_radius, F('friendly_rate'))))
        ).distance(finder_location).order_by('distance')[:limit]
```
returns the error 
```
D(km=min(10, F('friendly_rate'))))
TypeError: unorderable types: F() < int()
```

Any suggestions ? Details posted [here](https://stackoverflow.com/questions/52512683/understanding-this-django-based-geo-query-ffriendly-rate-and-km-unordera?noredirect=1#comment91965286_52512683) also

**Comment by andilabs** [comment]
@zedan185 have a look on newer version (python 3.6 django 2.1.5 + docker compose to run gently)
